### ISSUE TITLE
missing functionality in example?

### ISSUE THREAD

**Issue by Ryder17z** [Defmc/plog#1]
this will not create a log file. 

more information needed.

**Comment by Defmc** [comment]
Well, as described on README. You need to enable the `persistent` feature to save as a file. Along with it, set the `LOG_FILEPATH` env variable is also needed.
Cit.:
<html>
<body>


`persistent` | Add a persistent log handled by `LOG_FILEPATH` environment variable, saving each log on the pointed file | parking_lot | const_mutex for stable Rust and optimizations
-- | -- | -- | --



</body>
</html>

**Comment by Ryder17z** [comment]
I found a better crate to use.
